/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer'
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass'
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
// -1.52 2.54, 0.27
export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/duck_new.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      {/* <group position={[0, 0, -0.06]} rotation={[-1.52,2.54+((props.mouseY %1)*-1), 0.27+((props.mouseX %1)*1)]} scale={[0.07*300, 0.08*300, 0.08*300]}> */}
      <group position={[0, 0, -0.06]} rotation={[-1.52,props.coordx, props.coordy]} scale={[0.065*props.multi, 0.075*props.multi, 0.075*props.multi]}>
        <mesh material={materials.duck}  geometry={nodes['Sphere.001_0'].geometry} />
        <mesh material={materials.beak} geometry={nodes['Sphere.001_1'].geometry} />
        <mesh
          material={materials['Material.007']}
          geometry={nodes.duck_eyes.geometry}
          position={[0.79, 0.54, -0.12]}
          rotation={[-0.64, -0.23, 0.48]}
          scale={[0.08, 0.18, 0.21]}
        />
      </group>
    </group>
  )
}
